# Cloud Run service definition.
# This file provides a declarative configuration for the service.
# It can be used to deploy the service using `gcloud run services replace service.yaml`.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lost-loot-api
  annotations:
    # This annotation ensures that the service is updated by a CI/CD pipeline
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Limit outbound traffic to VPC connectors only
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      # The service account used by the service to access other Google Cloud services
      # This needs to have permissions for Firestore, Logging, etc.
      serviceAccountName: your-service-account@your-project-id.iam.gserviceaccount.com

      containers:
        - image: asia-south1-docker.pkg.dev/the-lost-loot-cloud/lost-loot-repo/lost-loot-api
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1000m'
              memory: '512Mi'

          # Environment variables passed to the container
          env:
            - name: NODE_ENV
              value: 'production'
            - name: LOG_LEVEL
              value: 'info'
            - name: CACHE_TTL
              value: '300' # 5 minutes

          # Liveness and readiness probes to ensure container health
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
